// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGf2D_q6ElTF60FWjqEar6U4zQScOKTU4',
    appId: '1:47025849345:web:b67581f7a7f11a8080ec00',
    messagingSenderId: '47025849345',
    projectId: 'anarrakshark-prod',
    authDomain: 'anarrakshark-prod.firebaseapp.com',
    storageBucket: 'anarrakshark-prod.firebasestorage.app',
    measurementId: 'G-S08D2ZGCTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5Ae7166ZXYPdShYPFAwtKTpuOX4ukLg',
    appId: '1:47025849345:android:c5cee43e37bc747380ec00',
    messagingSenderId: '47025849345',
    projectId: 'anarrakshark-prod',
    storageBucket: 'anarrakshark-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_aIExvH_oLsaOAxj2PuDwbBwFofBDJY',
    appId: '1:47025849345:ios:c79de979e80d77a180ec00',
    messagingSenderId: '47025849345',
    projectId: 'anarrakshark-prod',
    storageBucket: 'anarrakshark-prod.firebasestorage.app',
    iosBundleId: 'com.example.uiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_aIExvH_oLsaOAxj2PuDwbBwFofBDJY',
    appId: '1:47025849345:ios:c79de979e80d77a180ec00',
    messagingSenderId: '47025849345',
    projectId: 'anarrakshark-prod',
    storageBucket: 'anarrakshark-prod.firebasestorage.app',
    iosBundleId: 'com.example.uiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGf2D_q6ElTF60FWjqEar6U4zQScOKTU4',
    appId: '1:47025849345:web:f39651df07173d2080ec00',
    messagingSenderId: '47025849345',
    projectId: 'anarrakshark-prod',
    authDomain: 'anarrakshark-prod.firebaseapp.com',
    storageBucket: 'anarrakshark-prod.firebasestorage.app',
    measurementId: 'G-FB6QMV0WLE',
  );
}
